[package]
name = "noventa"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13.5"
actix-web = "4.11.0"
pyo3 = { version = "0.26.0", features = ["auto-initialize", "multiple-pymethods"] }
log = "0.4"
env_logger = "0.11.3"
minijinja = { version = "2.2.0", features = ["loader"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.5.0"
futures-util = "0.3.31"
serde_urlencoded = "0.7.1"
uuid = { version = "1.8.0", features = ["v4"] }

[build-dependencies]
pyo3-build-config = "0.22.0"
