# File uploading options

# Path to the static files directory. Can be relative or absolute.
# If commented out or not present, static file serving will be disabled.
static_path: "./files"

# The URL prefix for static files. Defaults to "/static" if not specified.
static_url_prefix: "/files"
# Maximum size in bytes for in-memory file uploads and are deleted after request is completed.
# Files larger than this will be streamed to a temporary file on disk.
# Default is 10 MB.
max_memory_size: 10485760 # 10 * 1024 * 1024

# Directory for temporary file uploads.
# If not specified, the system's temporary directory will be used.
temp_dir: "noventa-uploads"

# DoS and overload protection settings
adaptive_shedding: false

# Database connection URL for SQLAlchemy
database: "sqlite://noventa.db"

# Session configuration
session:
  # "cookie" for a client-side cookie store.
  # "in-memory" for a server-side, in-memory store.
  # "redis" for a server-side Redis store.
  backend: "in-memory"
  # IMPORTANT: A secret string at least 64 characters long.
  secret_key: "yaapejgyojczvsvsrtuvyucfghwwhzpieelbcnxbhnqipnqioqqgelodbfwmpqdk"
  # The name of the cookie that will be sent to the browser.
  cookie_name: "noventa_session"
  # If true, the cookie will only be sent over HTTPS. (Set to true in production)
  cookie_secure: false
  # If true, the cookie cannot be accessed by client-side JavaScript. (Highly recommended)
  cookie_http_only: true
  # The URL path for which the cookie is valid. "/" means the entire site.
  cookie_path: "/"
  # Max age seconds
  cookie_max_age: 30  # 1 day
  # Redis connection URL (used for session backend if enabled)
  redis_url: "redis://127.0.0.1/"
  redis_pool_size: 10